# .readthedocs.yaml

version: 2

# Build documentation inside a specific environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"  # Specify the Python version

# Define the steps for installing dependencies
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Command to build the documentation
sphinx:
  configuration: docs/source/conf.py

# # Custom commands
# commands:
#   - hatch env create docs  # Create the documentation environment using hatch
#   - hatch run docs:make html  # Use hatch to build the docs